spring:
  application:
    name: srs

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flashcard_srs}
    username: ${SPRING_DATASOURCE_USERNAME:srs_user}
    password: ${SPRING_DATASOURCE_PASSWORD:srs_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update # Tự động tạo hoặc cập nhật cấu trúc bảng
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  # Cấu hình Spring Mail (Dùng SMTP Gmail hoặc test SMTP tùy ý, ở đây tôi dùng cấu hình mẫu)
  mail:
    host: smtp.gmail.com
    port: 587
    username: quangdnis@gmail.com
    password: jxpw xirm soog npgx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Chuỗi secret (tối thiểu 256 bits cho HS256)
  expiration: 86400000 # 1 ngày
